version: 
2.1 jobs:
  build_test: 
    docker:
      - image: circleci/node:12 
      steps:
          checkout
        - run:
    name: Install pm dependencies
    command: |
        npm install --save
  build docker_image:
    docker:
      - image: circleci/node:12 
    steps:
      - checkout
      - setup_ remote_docker:
        docker_layer_caching: false
      - run:
    name: Build Docker image 
    command: |
    docker build -t nodejswebapp-t adijaiswal/nodejswebapp1:latest .
    echo $DOCKER_ PASSWORD | docker login -u adijaiswal --password-stdin docker push adijaiswal/nodejswebapp1:latest

workflows: 
  build_test: 
    jobs:
      - build_test
      - build_docker _image